The following Notebook fits a RNN to recognize characters which are hand written in Hindi.

    Import the necessary modules:

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator

    Set constants and paths that we might use:

In [8]:
TRAIN_DATA_DIR = '../Hindi-OCR/datasets/DevanagariHandwrittenCharacterDataset/Train/'
VALIDATION_DATA_DIR = '../Hindi-OCR/datasets/DevanagariHandwrittenCharacterDataset/Test/'
IMAGE_SIZE = (32, 32)
BATCH_SIZE = 64
NUM_CLASSES = 46

    Load the images using ImageDataGenerator:

In [9]:
train_datagen = ImageDataGenerator(rescale=1./255)
validation_datagen = ImageDataGenerator(rescale=1./255)

    Let's preprocess the images and perform aug..:

In [10]:
train_generator = train_datagen.flow_from_directory(
    TRAIN_DATA_DIR,
    target_size=IMAGE_SIZE,
    color_mode="grayscale",
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

validation_generator = validation_datagen.flow_from_directory(
    VALIDATION_DATA_DIR,
    target_size=IMAGE_SIZE,
    color_mode="grayscale",
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)


Found 78200 images belonging to 46 classes.
Found 13800 images belonging to 46 classes.


    Let's define the RNN architecture:

In [19]:

model = Sequential()

model.add(tf.keras.layers.Reshape((32, 32*3), input_shape=(32, 32, 3)))

model.add(SimpleRNN(128, activation='relu')) 
model.add(Flatten())
model.add(Dense(NUM_CLASSES, activation='softmax'))


    Congiure the RNN:

In [22]:
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape (Reshape)           (None, 32, 96)            0         
                                                                 
 simple_rnn_5 (SimpleRNN)    (None, 128)               28800     
                                                                 
 flatten_1 (Flatten)         (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 46)                5934      
                                                                 
Total params: 34734 (135.68 KB)
Trainable params: 34734 (135.68 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


    Fit the RNN:

In [23]:
history = model.fit(
    train_generator,  
    epochs=10,
    validation_data=validation_generator
)

Epoch 1/10


InvalidArgumentError: Graph execution error:

Detected at node sequential_5/reshape/Reshape defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1041, in launch_instance

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelapp.py", line 724, in start

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\tornado\platform\asyncio.py", line 215, in start

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 512, in dispatch_queue

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 501, in process_one

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 408, in dispatch_shell

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 731, in execute_request

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel\ipkernel.py", line 417, in do_execute

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\ipykernel\zmqshell.py", line 540, in run_cell

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 2945, in run_cell

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3000, in _run_cell

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3203, in run_cell_async

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3382, in run_ast_nodes

  File "C:\Users\Sanju\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code

  File "C:\Users\Sanju\AppData\Local\Temp\ipykernel_9220\4008986553.py", line 1, in <module>

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1783, in fit

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1377, in train_function

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1360, in step_function

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1349, in run_step

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 1126, in train_step

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py", line 589, in __call__

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\base_layer.py", line 1149, in __call__

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 96, in error_handler

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\sequential.py", line 398, in call

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\functional.py", line 515, in call

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\functional.py", line 672, in _run_internal_graph

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\base_layer.py", line 1149, in __call__

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\traceback_utils.py", line 96, in error_handler

  File "c:\Users\Sanju\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\reshaping\reshape.py", line 137, in call

Input to reshape is a tensor with 65536 values, but the requested shape has 196608
	 [[{{node sequential_5/reshape/Reshape}}]] [Op:__inference_train_function_1857]

In [25]:
x, y = next(train_generator)


(64, 32, 32, 1)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
